AdaptEMS.Web/Controllers/LeaveOrdersController.cs
using AdaptEMS.Entities.SharedEntities;
using AdaptEMS.Entities.SharedEntities.LeaveOrder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AdaptEMS.Web.Controllers
{
    public class LeaveOrdersController : WebBaseController
    {
        public LeaveOrdersController(IConfiguration configurations, IHttpContextAccessor contextAccessor) : base(configurations, contextAccessor)
        {
        }

        public async Task<IActionResult> Index()
        {
            var response = await CS.GetLeaveOrders();
            if (!response.Result)
            {
                Alert(Messages.ExceptionOccured, Consts.AdminNotificationType.error);
            }
            return View(response.Orders);
        }
        public async Task<IActionResult> Approve(int orderId)
        {
            var response = await CS.ApproveOrder(orderId);
            if (!response.Result)
            {
                Alert(Messages.ExceptionOccured, Consts.AdminNotificationType.error);
            }

            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Reject(int orderId)
        {
            var response = await CS.RejectOrder(orderId);
            if (!response.Result)
            {
                Alert(Messages.ExceptionOccured, Consts.AdminNotificationType.error);
            }

            return RedirectToAction(nameof(Index));
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(CreateLeaveOrderRequest model)
        {
            var response=await CS.CreateLeaveOrder(model);
            if (!response.Result)
            {
                Alert(response.Message, Consts.AdminNotificationType.error);
                return View(model);
            }
            else
            {
                Alert(Messages.Done, Consts.AdminNotificationType.success);
            }
            return View();
        }
        
    }
}

AdaptEMS.Web/Pages/Shared/_Layout.cshtml
@using System.Security.Claims
<html lang="en" dir="ltr">

<head>
    <meta>
    <!-- Twitter meta-->
    <meta property="twitter:card" content="summary_large_image">

    <meta property="og:type" content="website">
    <meta property="og:site_name" content="Vali Admin">
    <meta property="og:title" content="Vali - Free Bootstrap 4 admin theme">
    <meta property="og:url" content="http://pratikborsadiya.in/blog/vali-admin">
    <meta property="og:image" content="">

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Main CSS-->
    <link rel="stylesheet" type="text/css" href="~/css/main.css" asp-append-version="true">
    <link href="~/css/jquery.datatables.min.css" rel="stylesheet" asp-append-version="true" />
    <!-- Font-icon css-->
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body class="app sidebar-mini rtl">
    <partial name="_NotificationPanel" />
    <!-- Navbar-->
    <header class="app-header">
        <a class="app-header__logo" href="/">EMS</a>
        <!-- Sidebar toggle button-->
        <!-- Navbar Right Menu-->
        <ul class="app-nav">

            <!-- User Menu-->
            <li class="dropdown">
                <a class="app-nav__item" asp-controller="account" asp-action="logout" ><i class="fa fa-power-off"></i></a>
                
            </li>
        </ul>
    </header>
    <!-- Sidebar menu-->
    <div class="app-sidebar__overlay" data-toggle="sidebar"></div>
    <aside class="app-sidebar">
        <div class="app-sidebar__user">
            <center>
                @if (User.Identity.IsAuthenticated)
                {
                    <p class="app-sidebar__user-avatar">@User.Claims.FirstOrDefault(c => c.Type == Consts.UserNameClaimName).Value</p>
                }
            </center>
        </div>
        <ul class="app-menu">


            @if (User.Identities.First().Claims.FirstOrDefault(o => o.Type == Consts.RoleClaimName).Value.Contains(Consts.AdminAccountType))
            {
                <li><a asp-controller="Account" asp-action="GetEmployees" class="app-menu__item"><i class="app-menu__icon fa fa-user"></i><span class="app-menu__label">Employees</span></a></li>
                <li><a asp-controller="LeaveOrders" asp-action="Index" class="app-menu__item"><i class="app-menu__icon fa fa-user"></i><span class="app-menu__label">Leave Requests</span></a></li>

            }
            @if (User.Identities.First().Claims.FirstOrDefault(o => o.Type == Consts.RoleClaimName).Value.Contains(Consts.EmployeeAccountType))
            {
                <li><a asp-controller="LeaveOrders" asp-action="Create" class="app-menu__item"><i class="app-menu__icon fa fa-user"></i><span class="app-menu__label">Leave Requests</span></a></li>
            }
        </ul>
    </aside>

    <main class="app-content">
        @RenderBody()
    </main>
    <!-- Essential javascripts for application to work-->
    <script src="~/js/jquery-3.2.1.min.js"></script>
    <script src="~/js/popper.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/main.js"></script>
    <!-- The javascript plugin to display page loading on top-->
    <script src="~/js/plugins/pace.min.js"></script>
    <!-- Page specific javascripts-->
    <!-- Data table plugin-->
    <script src="~/js/jquery.datatables.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('table.dataTable').DataTable(
                {
                    /* Disable initial sort */
                    "aaSorting": [],
                    "columnDefs": [
                        { "searchable": false, "targets": [-1] },
                        { "class": "text-center", "targets": "_all" }
                    ]
                });
            $('.AllColumnSearchableTable').DataTable(
                {
                    /* Disable initial sort */
                    "aaSorting": [], "columnDefs": [{ "searchable": false, "targets": [-1] }]
                });

        })
    </script>
    <!-- Page specific javascripts-->
    <!-- Page specific javascripts-->
    <!-- Google analytics script-->
    <script type="text/javascript">
        if (document.location.hostname == 'pratikborsadiya.in') {
            (function (i, s, o, g, r, a, m) {
                i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
                    (i[r].q = i[r].q || []).push(arguments)
                }, i[r].l = 1 * new Date(); a = s.createElement(o),
                    m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
            })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');
            ga('create', 'UA-72504830-1', 'auto');
            ga('send', 'pageview');
        }
    </script>

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/sweetalert/sweetalert.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AdaptEMS.Web/Pages/Shared/_NotificationPanel.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/sweetalert/sweetalert.min.js"></script>
@{
    var callingString = "";
    if (TempData["notification"] != null)
    {
        callingString = TempData["notification"].ToString();
        TagBuilder script = new TagBuilder("script");
        script.InnerHtml.Append("$(document).ready(function () {" + callingString + "});");
        //script.ToString();
        var callingScript = "<script>$(document).ready(function () {" + callingString + "});</script>";

        @Html.Raw(callingScript);
        TempData["notification"] = null;
    }



}